### ISSUE TITLE
Docs for packaging

### ISSUE THREAD

**Issue by hirokiky** [jubatus/jubatus-python-client#53]
This package requires 'generating' before packaging.
I can't find way to run `generate.sh`. and I can't understand it well.
Don't you think it's nice to write down the way to create python packages?

I created just a fork project including generated files. https://github.com/hirokiky/jubatus-python-client

**Comment by hirokiky** [comment]
I wanted python supported version of jubatus client but it isn't. 
I tried to clone @unnonouno 's py3 branch and create python package, but I couldn't.

**Comment by kmaehashi** [comment]
Sorry for the delay of Python 3 support. We're planning to support it on the next month.

To use `generate.sh` to generate your own Python client, you need to build `jenerator`, a client code generator. See the document for the details: http://jubat.us/ja/server.html#id5
jenerator source is can be found in the main Jubatus repository: https://github.com/jubatus/jubatus/tree/master/tools/jenerator/

Before running `generate.sh` make sure to put `jenerator` in your `PATH` environment variable.

**Comment by hirokiky** [comment]
I made PR for this. please merge it if you like.
I know this description is not absolutely necessary.

**Comment by hirokiky** [comment]
Thanks for your help.
