### ISSUE TITLE
Python3: unittest prints error at last

### ISSUE THREAD

**Issue by kmaehashi** [jubatus/jubatus-python-client#57]
After running unittests, the following errors are printed:

```
Error in atexit._run_exitfuncs:
AttributeError: 'NoneType' object has no attribute 'items'
Error in atexit._run_exitfuncs:
AttributeError: 'NoneType' object has no attribute 'items'
```

This is because `concurrent` module is already unloaded when exiting Python process. We can workaround this issue by importing `concurrent` module in `setup.py` (so that the reference to the `concurrent` module is kept)

**Comment by rimms** [comment]
Fixed via #58
