### ISSUE TITLE
Anaconda: latest version of python client should be registered to Anaconda repositories.

### ISSUE THREAD

**Issue by shiodat** [jubatus/jubatus-python-client#63]
User "auto" registered OUT-OF-DATE jubatus-python-client 0.5.1 to Anaconda repository.
https://anaconda.org/auto/jubatus

My ambition is to register LATEST jubatus-python-client to Anaconda repository by Jubatus OSS community officially.

**Comment by shiodat** [comment]
We create an Anaconda account "jubatus" and upload the jubatus-python-client 0.8.2 PyPI package.
https://anaconda.org/jubatus/jubatus

The upload procedure is as follows: 
```
$ git clone https://github.com/jubatus/jubatus-python-client
$ cd jubatus-python-client
$ python setup.py sdist
$ anaconda upload dist/jubatus-0.8.2.tar.gz
```

**Comment by kmaehashi** [comment]
We'll close this issue after add this to the release procedure document.
