### ISSUE TITLE
Now tornado 4.5(which is latest version) didn't support python 2.6

### ISSUE THREAD

**Issue by yukimori** [jubatus/jubatus-python-client#77]
jubatus-python-client depends on some libraries. 
(jubatus-python-client -> messagepack-rpc-python -> tornado)

Now tornado 4.5(which is latest version) didn't support python 2.6.
So, jubatus-python-client depends on tornado under 4.4.3 if support python 2.6

ref:
jubatus/jubakit#84

**Comment by kmaehashi** [comment]
Fixed via #78
